const toggle=document.querySelector('.menu-toggle');
const mobileNav=document.querySelector('#mobile-nav');
function closeMenu(){toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','メニューを開く');mobileNav.hidden=true;}
toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'メニューを閉じる':'メニューを開く');mobileNav.hidden=!open;});
mobileNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!mobileNav.hidden){closeMenu();toggle.focus();}});
const modes={daily:{image:'assets/daily-use-image.jpeg',alt:'大型ショッピングモール入口でデジタルサイネージサポートサインを活用するイメージ',title:'毎日の情報発信に',copy:'施設案内掲示板自社の取り組み広告動画や画像で必要な情報をわかりやすく届けます',note:'活用イメージ：大型ショッピングモールでの情報発信'},emergency:{image:'assets/emergency-use-image.jpeg',alt:'避難所でデジタルサイネージサポートサインを使って支援物資を運搬する活用イメージ',title:'もしもの時の搬送の補助に',copy:'ディスプレイを取り外し製品タイプに応じた操作で搬送用具に車いすタイプは移動の補助や物資の運搬などに活用できます',note:'活用イメージ：緊急時の物資運搬'}};
document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>{const m=modes[button.dataset.mode];document.querySelectorAll('[data-mode]').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});const img=document.querySelector('#product-image');img.src=m.image;img.alt=m.alt;document.querySelector('#mode-title').textContent=m.title;document.querySelector('#mode-copy').textContent=m.copy;document.querySelector('#mode-note').textContent=m.note;}));
const scenes={public:['assets/community-new.jpeg','地域の支援拠点でサポートサインを活用するイメージ','活用イメージ / 公共施設','地域のお知らせともしもの備えを同じ場所に'],school:['assets/learning-new.jpeg','学校で車いす体験にサポートサインを活用するイメージ','活用イメージ / 学校','情報発信も防災学習も日々の学びのそばに'],factory:['assets/scene-factory.jpeg','工場内にサポートサインを設置し安全を呼びかける活用イメージ','活用イメージ / 工場・事業所','安全目標や連絡事項を従業員が集まる場所で'],transport:['assets/scene-port.jpeg','港のターミナルにサポートサインを設置する活用イメージ','活用イメージ / 駅・港','利用案内と移動を支える備えを'],stadium:['assets/scene-stadium.jpeg','サッカースタジアムの柱付近にサポートサインを設置する活用イメージ','活用イメージ / スポーツスタジアム','にぎわいのある場所にもしもの視点を']};
document.querySelectorAll('[data-scene]').forEach(detail=>detail.addEventListener('toggle',()=>{if(!detail.open)return;document.querySelectorAll('[data-scene]').forEach(d=>{if(d!==detail)d.open=false;});const s=scenes[detail.dataset.scene];const img=document.querySelector('#scene-image');img.src=s[0];img.alt=s[1];img.style.objectFit=['transport','stadium'].includes(detail.dataset.scene)?'contain':'cover';document.querySelector('#scene-image-label').textContent=s[2];document.querySelector('#scene-caption').textContent=s[3];}));
if('IntersectionObserver' in window&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}});},{threshold:.08});document.querySelectorAll('.intro-grid,.concept-bottom,.value-heading,.value-rows article,.support-grid article,.contact-intro').forEach(el=>{el.classList.add('reveal-ready');observer.observe(el);});}
document.querySelectorAll('.desktop-nav a[href="#about"],#mobile-nav a[href="#about"]').forEach(link=>link.href='product/');
const productStory=document.querySelector('.product-story');if(productStory&&!productStory.querySelector('a[href="product/"]')){const a=document.createElement('a');a.className='text-link';a.href='product/';a.innerHTML='製品について詳しく見る <span>↗</span>';productStory.append(a)}
