const toggle=document.querySelector('.menu-toggle');
const mobileNav=document.querySelector('#mobile-nav');
function closeMenu(){toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','メニューを開く');mobileNav.hidden=true;}
toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'メニューを閉じる':'メニューを開く');mobileNav.hidden=!open;});
mobileNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!mobileNav.hidden){closeMenu();toggle.focus();}});
const modes={daily:{image:'assets/daily-new.jpeg',alt:'ストレッチャータイプのサイネージ状態の実写真',title:'毎日の情報発信に',copy:'施設案内掲示板自社の取り組み広告動画や画像で必要な情報をわかりやすく届けます',note:'写真：ストレッチャータイプ／サイネージ状態'},emergency:{image:'assets/emergency-new.jpeg',alt:'避難所でサポートサインを使い支援物資を運搬する様子',title:'もしもの時の搬送の補助に',copy:'ディスプレイを取り外し製品タイプに応じた操作で搬送用具に車いすタイプは移動の補助や物資の運搬などに活用できます',note:'写真：緊急時の物資運搬'}};
document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>{const m=modes[button.dataset.mode];document.querySelectorAll('[data-mode]').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});const img=document.querySelector('#product-image');img.src=m.image;img.alt=m.alt;document.querySelector('#mode-title').textContent=m.title;document.querySelector('#mode-copy').textContent=m.copy;document.querySelector('#mode-note').textContent=m.note;}));
const scenes={public:['assets/community-new.jpeg','地域の支援拠点でサポートサインを活用するイメージ','活用イメージ / 公共施設','地域のお知らせともしもの備えを同じ場所に'],school:['assets/learning-new.jpeg','学校で車いす体験にサポートサインを活用するイメージ','活用イメージ / 学校','情報発信も防災学習も日々の学びのそばに'],factory:['assets/scene-factory.jpeg','工場内にサポートサインを設置し安全を呼びかける活用イメージ','活用イメージ / 工場・事業所','安全目標や連絡事項を従業員が集まる場所で'],transport:['assets/scene-port.jpeg','港のターミナルにサポートサインを設置する活用イメージ','活用イメージ / 駅・港','利用案内と移動を支える備えを'],stadium:['assets/scene-stadium.jpeg','サッカースタジアムの柱付近にサポートサインを設置する活用イメージ','活用イメージ / スポーツスタジアム','にぎわいのある場所にもしもの視点を']};
document.querySelectorAll('[data-scene]').forEach(detail=>detail.addEventListener('toggle',()=>{if(!detail.open)return;document.querySelectorAll('[data-scene]').forEach(d=>{if(d!==detail)d.open=false;});const s=scenes[detail.dataset.scene];const img=document.querySelector('#scene-image');img.src=s[0];img.alt=s[1];img.style.objectFit=['transport','stadium'].includes(detail.dataset.scene)?'contain':'cover';document.querySelector('#scene-image-label').textContent=s[2];document.querySelector('#scene-caption').textContent=s[3];}));
document.querySelector('#contact-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);const body=`株式会社ユニオン 営業部 ご担当者様\n\nデジタルサイネージサポートサインについて質問です\n\n${data.get('message')}\n\nお名前：${data.get('name')||'未記入'}\n会社名・施設名：${data.get('company')||'未記入'}`;window.location.href='mailto:union1@abeam.ocn.ne.jp?subject='+encodeURIComponent('デジタルサイネージサポートサインについての質問')+'&body='+encodeURIComponent(body);document.querySelector('#form-status').textContent='メールアプリで内容を確認し送信してください開かない場合は上記メールアドレスまたはお電話からお問い合わせください';});
if('IntersectionObserver' in window&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}});},{threshold:.08});document.querySelectorAll('.intro-grid,.concept-bottom,.value-heading,.value-rows article,.support-grid article,.contact-intro').forEach(el=>{el.classList.add('reveal-ready');observer.observe(el);});}
